"""empty message

Revision ID: 1c8c466606a8
Revises: 
Create Date: 2024-07-18 10:16:15.317209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8c466606a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mueble',
    sa.Column('id_codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('color', sa.Enum('Natural', 'Blanco/Beig/Gris', 'Negro/Gris Oscuro', 'Tonos Pastel', 'Tonos Vivos', 'Dorado/Plateado', name='color_mueble'), nullable=False),
    sa.Column('espacio', sa.Enum('salón/comedor', 'dormitorio', 'recibidor', 'zona de trabajo', 'exterior', 'otras', name='espacio_mueble'), nullable=False),
    sa.Column('estilo', sa.Enum('industrial', 'clásico', 'minimalista', 'nórdico', 'rústico', 'vintage/mid-century', 'otras', name='estilo_mueble'), nullable=False),
    sa.Column('categoria', sa.Enum('armarios y cómodas', 'estanterias y baldas', 'mesas y escritorios', 'aparadores', 'camas y cabaceros', 'mesillas', 'sillones y sofás', 'lámparas', 'sillas y taburetes', 'percheros', 'marcos y espejos', 'otros objetos', name='categoria_mueble'), nullable=False),
    sa.Column('precio_mes', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega', sa.String(), nullable=True),
    sa.Column('fecha_recogida', sa.String(), nullable=True),
    sa.Column('ancho', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('fondo', sa.Float(), nullable=False),
    sa.Column('personalidad', sa.String(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_codigo')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alquiler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('pago_mensual', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mueble_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mueble_id'], ['mueble.id_codigo'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mueble_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mueble_id'], ['mueble.id_codigo'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    op.drop_table('alquiler')
    op.drop_table('user')
    op.drop_table('mueble')
    # ### end Alembic commands ###
