"""empty message

Revision ID: bf44d90253b5
Revises: aabcb308a7a1
Create Date: 2024-07-15 18:20:29.327938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf44d90253b5'
down_revision = 'aabcb308a7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mueble', schema=None) as batch_op:
        batch_op.alter_column('fecha_entrega',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('fecha_recogida',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mueble', schema=None) as batch_op:
        batch_op.alter_column('fecha_recogida',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('fecha_entrega',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
